// MPC Global - Clinical Scheduling Dataset (Based on Wednesday 02-09 Schedule)

const CLINIC_DATA = {
  date: "2026-09-02",
  dateFormatted: "Wednesday, 02-09-2026",
  clinicName: "My Pain Clinic Global",
  
  // Status definitions & color codes (Exact Google Sheet Palette)
  statuses: {
    available: { label: "Available", color: "#ffffff", border: "#4285f4", textColor: "#1a73e8", icon: "□" },
    booked: { label: "Booked", bg: "#4285f4", textColor: "#ffffff", icon: "🟦" },
    ready: { label: "Ready", bg: "#34a853", textColor: "#ffffff", icon: "🟢" },
    in_progress: { label: "In Progress", bg: "#fbbc04", textColor: "#202124", icon: "🟡" },
    break: { label: "Break", bg: "#5f6368", textColor: "#ffffff", icon: "⬛" },
    cancelled: { label: "Cancelled", bg: "#ea4335", textColor: "#ffffff", icon: "🟥" },
    absent: { label: "Absent", bg: "#9aa0a6", textColor: "#ffffff", icon: "⬜" },
    completed: { label: "Completed", bg: "#5f6368", textColor: "#ffffff", icon: "✓" }
  },

  // Doctors list with supported services, location, working hours, and real capacity
  doctors: [
    {
      id: "doc-vidisha",
      name: "Dr. Vidhisha Kotian",
      specialty: "Senior MSK Specialist",
      floor: "Upstairs MSK",
      avatar: "VK",
      primaryService: "AMSK",
      primaryServiceLabel: "Advance Physio (AMSK)",
      supportedServices: ["AMSK"],
      workingHours: { start: "09:30", end: "18:00" },
      lunchTime: { start: "13:30", end: "14:00" },
      status: "busy",
      freeFor: "45 min",
      nextAppointment: "12:30 PM",
      rating: "4.9",
      totalToday: 8
    },
    {
      id: "doc-diwakar",
      name: "Dr. Diwakar Mishra",
      specialty: "MSK & Spine Specialist",
      floor: "Upstairs MSK",
      avatar: "DM",
      primaryService: "AMSK",
      primaryServiceLabel: "Advance Physio (AMSK)",
      supportedServices: ["AMSK"],
      workingHours: { start: "10:30", end: "19:00" },
      lunchTime: { start: "13:30", end: "14:00" },
      status: "available",
      freeFor: "1 hr",
      nextAppointment: "10:30 AM",
      rating: "4.8",
      totalToday: 8
    },
    {
      id: "doc-krishna",
      name: "Dr. Krishna Katkar",
      specialty: "MSK & Laser Consultant",
      floor: "Upstairs MSK",
      avatar: "KK",
      primaryService: "AMSK",
      primaryServiceLabel: "Advance Physio (AMSK)",
      supportedServices: ["AMSK"],
      workingHours: { start: "09:30", end: "18:00" },
      lunchTime: { start: "13:30", end: "14:00" },
      status: "busy",
      freeFor: "30 min",
      nextAppointment: "12:30 PM",
      rating: "4.9",
      totalToday: 8
    },
    {
      id: "doc-hardi",
      name: "Dr. Hardi Mehta",
      specialty: "MSK & Rehab Specialist",
      floor: "Downstairs MSK",
      avatar: "HM",
      primaryService: "AMSK",
      primaryServiceLabel: "Advance Physio (AMSK)",
      supportedServices: ["AMSK"],
      workingHours: { start: "12:30", end: "20:00" },
      lunchTime: { start: "13:30", end: "14:00" },
      status: "busy",
      freeFor: "0 min",
      nextAppointment: "12:30 PM",
      rating: "4.8",
      totalToday: 7
    },
    {
      id: "doc-spoorthi",
      name: "Dr. Spoorthi Poojary",
      specialty: "MSK & Spine Decompression",
      floor: "Downstairs MSK",
      avatar: "SP",
      primaryService: "AMSK",
      primaryServiceLabel: "Advance Physio (AMSK)",
      supportedServices: ["AMSK"],
      workingHours: { start: "11:30", end: "20:00" },
      lunchTime: { start: "13:30", end: "14:00" },
      status: "available",
      freeFor: "1 hr",
      nextAppointment: "11:30 AM",
      rating: "4.7",
      totalToday: 8
    },
    {
      id: "doc-saurambika",
      name: "Dr. Saurambika Shukla",
      specialty: "Downstairs PT Specialist",
      floor: "Downstairs PT",
      avatar: "SS",
      primaryService: "AMSK",
      primaryServiceLabel: "Downstairs PT",
      supportedServices: ["AMSK", "DTT"],
      workingHours: { start: "11:30", end: "20:30" },
      lunchTime: { start: "14:00", end: "14:30" },
      status: "available",
      freeFor: "2 hrs",
      nextAppointment: "11:30 AM",
      rating: "4.9",
      totalToday: 8
    },
    {
      id: "doc-sakshi-b",
      name: "Dr. Sakshi Bhardwaj",
      specialty: "DTT & Thermal Specialist",
      floor: "Therapy Wing",
      avatar: "SB",
      primaryService: "DTT",
      primaryServiceLabel: "DTT / ACW",
      supportedServices: ["DTT", "ACW"],
      workingHours: { start: "09:00", end: "18:00" },
      lunchTime: { start: "13:30", end: "14:00" },
      status: "busy",
      freeFor: "0 min",
      nextAppointment: "12:30 PM",
      rating: "4.7",
      totalToday: 9
    },
    {
      id: "doc-anjali-k",
      name: "Dr. Anjali Kamble",
      specialty: "DTT & Myofascial Specialist",
      floor: "Therapy Pods",
      avatar: "AK",
      primaryService: "DTT",
      primaryServiceLabel: "DTT / ACW",
      supportedServices: ["DTT", "ACW"],
      workingHours: { start: "09:00", end: "18:00" },
      lunchTime: { start: "13:30", end: "14:00" },
      status: "busy",
      freeFor: "30 min",
      nextAppointment: "01:00 PM",
      rating: "4.8",
      totalToday: 9
    },
    {
      id: "doc-shifa",
      name: "Dr. Shifa Sayyed",
      specialty: "Laser & Spine Specialist",
      floor: "Treatment Suites",
      avatar: "SS",
      primaryService: "THOR",
      primaryServiceLabel: "THOR Laser",
      supportedServices: ["THOR", "FOCUSED_SW"],
      workingHours: { start: "09:00", end: "20:00" },
      lunchTime: { start: "13:30", end: "14:00" },
      status: "busy",
      freeFor: "15 min",
      nextAppointment: "12:30 PM",
      rating: "4.9",
      totalToday: 11
    },
    {
      id: "doc-daniya",
      name: "Dr. Daniya Philips",
      specialty: "Magneto & Laser Consultant",
      floor: "Laser Wing",
      avatar: "DP",
      primaryService: "MAGNETO",
      primaryServiceLabel: "Magneto / PEMF",
      supportedServices: ["MAGNETO", "THOR"],
      workingHours: { start: "10:00", end: "20:30" },
      lunchTime: { start: "13:30", end: "14:00" },
      status: "available",
      freeFor: "1 hr",
      nextAppointment: "01:30 PM",
      rating: "4.8",
      totalToday: 8
    },
    {
      id: "doc-ankita",
      name: "Dr. Ankita Kumari Sharma",
      specialty: "Magneto & PEMF Specialist",
      floor: "PEMF Suite",
      avatar: "AS",
      primaryService: "MAGNETO",
      primaryServiceLabel: "Magneto / PEMF",
      supportedServices: ["MAGNETO"],
      workingHours: { start: "11:00", end: "20:00" },
      lunchTime: { start: "14:00", end: "14:30" },
      status: "available",
      freeFor: "2 hrs 15 min",
      nextAppointment: "04:00 PM",
      rating: "4.8",
      totalToday: 7
    },
    {
      id: "doc-sakshi-s",
      name: "Dr. Sakshi Singh",
      specialty: "Class 4 Laser & RBA",
      floor: "Robotic Suite",
      avatar: "SS",
      primaryService: "HIL",
      primaryServiceLabel: "Class 4 Laser / RBA",
      supportedServices: ["HIL", "RBA", "MAGNETO"],
      workingHours: { start: "09:00", end: "18:00" },
      lunchTime: { start: "13:30", end: "14:00" },
      status: "available",
      freeFor: "1 hr",
      nextAppointment: "01:30 PM",
      rating: "4.9",
      totalToday: 8
    },
    {
      id: "doc-spine-d",
      name: "Dr. Reena Patel",
      specialty: "Spine Decompression Specialist",
      floor: "Spine Decompression Suite",
      avatar: "RP",
      primaryService: "SPINE_D",
      primaryServiceLabel: "Spine Decompression",
      supportedServices: ["SPINE_D"],
      workingHours: { start: "09:00", end: "18:00" },
      lunchTime: { start: "13:30", end: "14:00" },
      status: "available",
      freeFor: "1 hr",
      nextAppointment: "09:30 AM",
      rating: "4.9",
      totalToday: 5
    },
    {
      id: "doc-hbot-hard",
      name: "Dr. Anjali Dalwadi",
      specialty: "HBOT Hard Specialist",
      floor: "Hyperbaric Suite",
      avatar: "AD",
      primaryService: "HBOT_HARD",
      primaryServiceLabel: "HBOT (Hard Shell)",
      supportedServices: ["HBOT_HARD"],
      workingHours: { start: "09:00", end: "18:00" },
      lunchTime: { start: "13:30", end: "14:00" },
      status: "busy",
      freeFor: "30 min",
      nextAppointment: "10:00 AM",
      rating: "4.9",
      totalToday: 5
    },
    {
      id: "doc-hbot-soft",
      name: "Dr. Anjali Dalwadi",
      specialty: "HBOT Soft Specialist",
      floor: "Hyperbaric Suite",
      avatar: "AD",
      primaryService: "HBOT_SOFT",
      primaryServiceLabel: "HBOT (Soft Shell)",
      supportedServices: ["HBOT_SOFT"],
      workingHours: { start: "09:00", end: "18:00" },
      lunchTime: { start: "13:30", end: "14:00" },
      status: "available",
      freeFor: "1 hr",
      nextAppointment: "10:00 AM",
      rating: "4.9",
      totalToday: 6
    },
    {
      id: "doc-red-light",
      name: "Dr. Anjali Dalwadi",
      specialty: "Red Light Therapy Specialist",
      floor: "Wellness Suite",
      avatar: "AD",
      primaryService: "RED_LIGHT",
      primaryServiceLabel: "Red Light Therapy",
      supportedServices: ["RED_LIGHT"],
      workingHours: { start: "09:00", end: "18:00" },
      lunchTime: { start: "13:30", end: "14:00" },
      status: "available",
      freeFor: "30 min",
      nextAppointment: "09:00 AM",
      rating: "4.9",
      totalToday: 5
    },
    {
      id: "doc-foot-insoles",
      name: "Dr. Anjali Dalwadi",
      specialty: "Foot Insoles Specialist",
      floor: "Wellness Suite",
      avatar: "AD",
      primaryService: "RED_FOOT_INSOLES",
      primaryServiceLabel: "Foot Insoles",
      supportedServices: ["RED_FOOT_INSOLES"],
      workingHours: { start: "09:00", end: "18:00" },
      lunchTime: { start: "13:30", end: "14:00" },
      status: "available",
      freeFor: "1 hr",
      nextAppointment: "10:30 AM",
      rating: "4.9",
      totalToday: 4
    },
    {
      id: "doc-pelvic-chair",
      name: "Dr. Anjali Dalwadi",
      specialty: "Pelvic Chair Specialist",
      floor: "Wellness Suite",
      avatar: "AD",
      primaryService: "PELVIC_CHAIR",
      primaryServiceLabel: "Pelvic Chair",
      supportedServices: ["PELVIC_CHAIR"],
      workingHours: { start: "09:00", end: "18:00" },
      lunchTime: { start: "13:30", end: "14:00" },
      status: "available",
      freeFor: "30 min",
      nextAppointment: "11:00 AM",
      rating: "4.9",
      totalToday: 5
    }
  ],

  // Services Catalog with exact colors from the physical schedule sheet
  services: [
    {
      id: "AMSK",
      name: "Advance Physiotherapy (AMSK)",
      shortName: "Advance Physio",
      durationMinutes: 60,
      durationLabel: "1 Hour",
      category: "Physiotherapy",
      color: "#1155cc",
      description: "Advanced Musculoskeletal manipulation, targeted dry needling and bespoke rehabilitation."
    },
    {
      id: "DTT",
      name: "Deep Tissue Thermotherapy (DTT)",
      shortName: "DTT",
      durationMinutes: 30,
      durationLabel: "30 Minutes",
      category: "Thermal Therapy",
      color: "#ff9900",
      description: "Targeted radiofrequency thermal tissue regeneration and deep myofascial release."
    },
    {
      id: "THOR",
      name: "THOR Laser",
      shortName: "THOR Laser",
      durationMinutes: 30,
      durationLabel: "30 Minutes",
      category: "Photobiomodulation",
      color: "#00acc1",
      description: "Cold laser photobiomodulation for acute pain, tissue repair, and rapid cellular healing."
    },
    {
      id: "MAGNETO",
      name: "Magneto Laser (PEMF)",
      shortName: "Magneto Laser",
      durationMinutes: 30,
      durationLabel: "30 Minutes",
      category: "Electromagnetic",
      color: "#9900ff",
      description: "High-intensity pulsed electromagnetic field therapy for deep cellular stimulation."
    },
    {
      id: "RBA",
      name: "Robotic Spine Aligner (RBA)",
      shortName: "Robotic Spine",
      durationMinutes: 30,
      durationLabel: "30 Minutes",
      category: "Spine & Robotics",
      color: "#4a86e8",
      description: "Precision computer-guided robotic vertebral mobilization and biomechanical alignment."
    },
    {
      id: "HIL",
      name: "High Intensity Laser (Class 4)",
      shortName: "Class 4 Laser",
      durationMinutes: 30,
      durationLabel: "30 Minutes",
      category: "Laser Therapy",
      color: "#a64d79",
      description: "Deep tissue photothermal stimulation with high-powered therapeutic laser."
    },
    {
      id: "FOCUSED_SW",
      name: "Focused Shockwave Therapy",
      shortName: "Focused Shockwave",
      durationMinutes: 30,
      durationLabel: "30 Minutes",
      category: "Acoustic Waves",
      color: "#f1c232",
      description: "Targeted focused acoustic energy for calcifications, chronic tendonitis, and trigger points."
    },
    {
      id: "ACW",
      name: "Acoustic Wave Therapy (ACW)",
      shortName: "Acoustic Wave",
      durationMinutes: 30,
      durationLabel: "30 Minutes",
      category: "Acoustic Waves",
      color: "#34a853",
      description: "Radial acoustic pressure waves for soft tissue mobility, fascial release, and micro-circulation."
    },
    {
      id: "SPINE_D",
      name: "Spine Decompression",
      shortName: "Spine Decompression",
      durationMinutes: 30,
      durationLabel: "30 Minutes",
      category: "Spine & Robotics",
      color: "#00acc1",
      description: "Non-surgical computerized spinal traction and disc pressure reduction."
    },
    {
      id: "HBOT_HARD",
      name: "HBOT (Hard Shell)",
      shortName: "HBOT Hard",
      durationMinutes: 60,
      durationLabel: "1 Hour",
      category: "Oxygen & Recovery",
      color: "#1155cc",
      description: "High pressure 2.0 ATA medical grade 100% hyperbaric oxygen chamber."
    },
    {
      id: "HBOT_SOFT",
      name: "HBOT (Soft Shell)",
      shortName: "HBOT Soft",
      durationMinutes: 60,
      durationLabel: "1 Hour",
      category: "Oxygen & Recovery",
      color: "#4285f4",
      description: "Mild hyperbaric 1.3 - 1.5 ATA oxygen therapy for systemic anti-inflammatory recovery."
    },
    {
      id: "RED_LIGHT",
      name: "Red Light Therapy",
      shortName: "Red Light",
      durationMinutes: 30,
      durationLabel: "30 Minutes",
      category: "Photobiomodulation",
      color: "#dc2626",
      description: "Full-body clinical LED red and near-infrared light phototherapy bed."
    },
    {
      id: "ICE_BATH",
      name: "Ice Bath",
      shortName: "Ice Bath",
      durationMinutes: 30,
      durationLabel: "30 Minutes",
      category: "Cryo & Thermal",
      color: "#00bcd4",
      description: "Sub-10°C cold water immersion for vascular constriction and inflammation flushing."
    },
    {
      id: "CRYOTHERAPY",
      name: "Cryotherapy",
      shortName: "Cryotherapy",
      durationMinutes: 30,
      durationLabel: "30 Minutes",
      category: "Cryo & Thermal",
      color: "#0097a7",
      description: "Whole-body ultra-cold vapor exposure (-110°C) for systemic metabolic and pain relief."
    },
    {
      id: "BMSK",
      name: "Basic Physiotherapy (BMSK)",
      shortName: "Basic Physio",
      durationMinutes: 45,
      durationLabel: "45 Minutes",
      category: "Physiotherapy",
      color: "#999999",
      description: "Standard physical rehabilitation, assisted stretches, and core strengthening exercises."
    },
    {
      id: "PELVIC_CHAIR",
      name: "Pelvic Chair / Foot Insole",
      shortName: "Pelvic Chair",
      durationMinutes: 30,
      durationLabel: "30 Minutes",
      category: "Specialized",
      color: "#9900ff",
      description: "High-intensity focused electromagnetic pelvic floor stimulation and custom biomechanical insoles."
    },
    {
      id: "RED_FOOT_INSOLES",
      name: "Foot Insoles",
      shortName: "Foot Insoles",
      durationMinutes: 30,
      durationLabel: "30 Minutes",
      category: "Specialized",
      color: "#e11d48",
      description: "Customized therapeutic foot insole fitting, gait analysis and biomechanical pressure mapping."
    },
    {
      id: "CONSULTATION",
      name: "Doctor Consultation / Follow Up",
      shortName: "Consultation",
      durationMinutes: 30,
      durationLabel: "30 Minutes",
      category: "Consultations",
      color: "#5f6368",
      description: "Initial diagnostic clinical evaluation, posture assessment, or progress follow-up."
    }
  ],

  // Standard 30-min slots for all other services
  halfHourTimeSlots: [
    { start: "09:00", end: "09:30", label: "09:00 AM - 09:30 AM" },
    { start: "09:30", end: "10:00", label: "09:30 AM - 10:00 AM" },
    { start: "10:00", end: "10:30", label: "10:00 AM - 10:30 AM" },
    { start: "10:30", end: "11:00", label: "10:30 AM - 11:00 AM" },
    { start: "11:00", end: "11:30", label: "11:00 AM - 11:30 AM" },
    { start: "11:30", end: "12:00", label: "11:30 AM - 12:00 PM" },
    { start: "12:00", end: "12:30", label: "12:00 PM - 12:30 PM" },
    { start: "12:30", end: "13:00", label: "12:30 PM - 01:00 PM" },
    { start: "13:00", end: "13:30", label: "01:00 PM - 01:30 PM" },
    { start: "13:30", end: "14:00", label: "01:30 PM - 02:00 PM" }, // Lunch
    { start: "14:00", end: "14:30", label: "02:00 PM - 02:30 PM" },
    { start: "14:30", end: "15:00", label: "02:30 PM - 03:00 PM" },
    { start: "15:00", end: "15:30", label: "03:00 PM - 03:30 PM" },
    { start: "15:30", end: "16:00", label: "03:30 PM - 04:00 PM" },
    { start: "16:00", end: "16:30", label: "04:00 PM - 04:30 PM" },
    { start: "16:30", end: "17:00", label: "04:30 PM - 05:00 PM" },
    { start: "17:00", end: "17:30", label: "05:00 PM - 05:30 PM" },
    { start: "17:30", end: "18:00", label: "05:30 PM - 06:00 PM" },
    { start: "18:00", end: "18:30", label: "06:00 PM - 06:30 PM" },
    { start: "18:30", end: "19:00", label: "06:30 PM - 07:00 PM" },
    { start: "19:00", end: "19:30", label: "07:00 PM - 07:30 PM" },
    { start: "19:30", end: "20:00", label: "07:30 PM - 08:00 PM" },
    { start: "20:00", end: "20:30", label: "08:00 PM - 08:30 PM" }
  ],

  // Specific 1-Hour standard slots for Advance Physiotherapy (AMSK)
  amskTimeSlots: [
    { start: "09:30", end: "10:30", label: "09:30 AM - 10:30 AM" },
    { start: "10:30", end: "11:30", label: "10:30 AM - 11:30 AM" },
    { start: "11:30", end: "12:30", label: "11:30 AM - 12:30 PM" },
    { start: "12:30", end: "13:30", label: "12:30 PM - 01:30 PM" },
    { start: "13:30", end: "14:00", label: "01:30 PM - 02:00 PM" }, // Lunch
    { start: "14:00", end: "15:00", label: "02:00 PM - 03:00 PM" },
    { start: "15:00", end: "16:00", label: "03:00 PM - 04:00 PM" },
    { start: "16:00", end: "17:00", label: "04:00 PM - 05:00 PM" },
    { start: "17:00", end: "18:00", label: "05:00 PM - 06:00 PM" },
    { start: "18:00", end: "19:00", label: "06:00 PM - 07:00 PM" },
    { start: "19:00", end: "20:00", label: "07:00 PM - 08:00 PM" }
  ],

  // Default timeSlots pointing to half-hour slots
  timeSlots: [
    { start: "09:00", end: "09:30", label: "09:00 AM - 09:30 AM" },
    { start: "09:30", end: "10:00", label: "09:30 AM - 10:00 AM" },
    { start: "10:00", end: "10:30", label: "10:00 AM - 10:30 AM" },
    { start: "10:30", end: "11:00", label: "10:30 AM - 11:00 AM" },
    { start: "11:00", end: "11:30", label: "11:00 AM - 11:30 AM" },
    { start: "11:30", end: "12:00", label: "11:30 AM - 12:00 PM" },
    { start: "12:00", end: "12:30", label: "12:00 PM - 12:30 PM" },
    { start: "12:30", end: "13:00", label: "12:30 PM - 01:00 PM" },
    { start: "13:00", end: "13:30", label: "01:00 PM - 01:30 PM" },
    { start: "13:30", end: "14:00", label: "01:30 PM - 02:00 PM" },
    { start: "14:00", end: "14:30", label: "02:00 PM - 02:30 PM" },
    { start: "14:30", end: "15:00", label: "02:30 PM - 03:00 PM" },
    { start: "15:00", end: "15:30", label: "03:00 PM - 03:30 PM" },
    { start: "15:30", end: "16:00", label: "03:30 PM - 04:00 PM" },
    { start: "16:00", end: "16:30", label: "04:00 PM - 04:30 PM" },
    { start: "16:30", end: "17:00", label: "04:30 PM - 05:00 PM" },
    { start: "17:00", end: "17:30", label: "05:00 PM - 05:30 PM" },
    { start: "17:30", end: "18:00", label: "05:30 PM - 06:00 PM" },
    { start: "18:00", end: "18:30", label: "06:00 PM - 06:30 PM" },
    { start: "18:30", end: "19:00", label: "06:30 PM - 07:00 PM" },
    { start: "19:00", end: "19:30", label: "07:00 PM - 07:30 PM" },
    { start: "19:30", end: "20:00", label: "07:30 PM - 08:00 PM" },
    { start: "20:00", end: "20:30", label: "08:00 PM - 08:30 PM" }
  ],

  // Real Appointments from the clinic schedule
  appointments: [
    // --- Dr. Vidisha Kotian (AMSK) ---
    {
      id: "apt-101",
      patientId: "p-001",
      patientName: "BASANTI JAIN",
      doctor: "doc-vidisha",
      service: "AMSK",
      startTime: "09:30",
      endTime: "10:30",
      timeLabel: "09:30 AM – 10:30 AM",
      status: "ready",
      notes: "Cervical radiculopathy, gentle mobilization",
      packageRemaining: "6 of 10 sessions",
      phone: "+91 98201 44521"
    },
    {
      id: "apt-102",
      patientId: "p-002",
      patientName: "RUKHSHANA SHOLAPURWALA",
      doctor: "doc-vidisha",
      service: "AMSK",
      startTime: "09:30",
      endTime: "10:30",
      timeLabel: "9:30 AM – 10:30 AM",
      status: "booked",
      notes: "Lumbar Disc L4-L5, dry needling session 4",
      packageRemaining: "4 of 12 sessions",
      phone: "+91 98192 11093"
    },
    {
      id: "apt-103",
      patientId: "p-003",
      patientName: "RANI MHATRE",
      doctor: "doc-vidisha",
      service: "AMSK",
      startTime: "10:30",
      endTime: "11:30",
      timeLabel: "10:30 AM – 11:30 AM",
      status: "booked",
      notes: "Knee osteoarthritis grade 2",
      packageRemaining: "8 of 10 sessions",
      phone: "+91 97693 88120"
    },
    {
      id: "apt-104",
      patientId: "p-004",
      patientName: "DHARMISHTHA VORA",
      doctor: "doc-vidisha",
      service: "AMSK",
      startTime: "11:30",
      endTime: "12:30",
      timeLabel: "11:30 AM – 12:30 PM",
      status: "ready",
      notes: "Post-op shoulder rotator cuff repair",
      packageRemaining: "2 of 6 sessions",
      phone: "+91 98210 99432"
    },
    {
      id: "apt-105",
      patientId: "p-005",
      patientName: "MEREENA DESOUZA",
      doctor: "doc-vidisha",
      service: "AMSK",
      startTime: "12:30",
      endTime: "13:30",
      timeLabel: "12:30 PM – 1:30 PM",
      status: "in_progress",
      notes: "Upper thoracic stiffness, needs trigger point release",
      packageRemaining: "5 of 10 sessions",
      phone: "+91 98334 55102"
    },
    {
      id: "apt-106",
      patientId: "p-006",
      patientName: "SHEETAL SHAH",
      doctor: "doc-vidisha",
      service: "AMSK",
      startTime: "14:00",
      endTime: "15:00",
      timeLabel: "2:00 PM – 3:00 PM",
      status: "booked",
      notes: "NO NEEDLING today, manual manipulation only",
      packageRemaining: "7 of 10 sessions",
      phone: "+91 99200 44321"
    },
    {
      id: "apt-107",
      patientId: "p-007",
      patientName: "SHASHIKALA VAIRAGAR",
      doctor: "doc-vidisha",
      service: "AMSK",
      startTime: "15:00",
      endTime: "16:00",
      timeLabel: "3:00 PM – 4:00 PM",
      status: "booked",
      notes: "Dr Spoorthi room shared",
      packageRemaining: "3 of 8 sessions",
      phone: "+91 98205 66781"
    },
    {
      id: "apt-108",
      patientId: "p-008",
      patientName: "DEEPA OBEROI",
      doctor: "doc-vidisha",
      service: "AMSK",
      startTime: "16:00",
      endTime: "17:00",
      timeLabel: "4:00 PM – 5:00 PM",
      status: "booked",
      notes: "Bilateral plantar fasciitis",
      packageRemaining: "9 of 10 sessions",
      phone: "+91 98199 22345"
    },
    {
      id: "apt-109",
      patientId: "p-009",
      patientName: "IQBAL SHAIKH",
      doctor: "doc-vidisha",
      service: "AMSK",
      startTime: "17:00",
      endTime: "18:00",
      timeLabel: "5:00 PM – 6:00 PM",
      status: "booked",
      notes: "Followed by HBOT at 6:30 PM",
      packageRemaining: "1 of 5 sessions",
      phone: "+91 97688 00192"
    },

    // --- Dr. Diwakar Mishra (AMSK & THOR) ---
    {
      id: "apt-201",
      patientId: "p-010",
      patientName: "VIKRANT KAVITAKE",
      doctor: "doc-diwakar",
      service: "AMSK",
      startTime: "10:30",
      endTime: "11:30",
      timeLabel: "10:30 AM – 11:30 AM",
      status: "in_progress",
      notes: "DR DIWAKAR ONLY - Acute sciatica",
      packageRemaining: "3 of 10 sessions",
      phone: "+91 98200 12399"
    },
    {
      id: "apt-202",
      patientId: "p-011",
      patientName: "SUMIT PAKHALE",
      doctor: "doc-diwakar",
      service: "AMSK",
      startTime: "11:30",
      endTime: "12:30",
      timeLabel: "11:30 AM – 12:30 PM",
      status: "booked",
      notes: "Lumbar spine decompression protocol",
      packageRemaining: "5 of 12 sessions",
      phone: "+91 99201 88472"
    },
    {
      id: "apt-203",
      patientId: "p-012",
      patientName: "GOVIND KHETAN",
      doctor: "doc-diwakar",
      service: "AMSK",
      startTime: "12:30",
      endTime: "13:30",
      timeLabel: "12:30 PM – 1:30 PM",
      status: "booked",
      notes: "Confirmed on WhatsApp",
      packageRemaining: "6 of 8 sessions",
      phone: "+91 98331 44556"
    },
    {
      id: "apt-204",
      patientId: "p-013",
      patientName: "DEEPAK SAKPAL",
      doctor: "doc-diwakar",
      service: "AMSK",
      startTime: "14:00",
      endTime: "15:00",
      timeLabel: "2:00 PM – 3:00 PM",
      status: "booked",
      notes: "Thoracic alignment check",
      packageRemaining: "2 of 6 sessions",
      phone: "+91 98190 77665"
    },
    {
      id: "apt-205",
      patientId: "p-014",
      patientName: "SHAKIL KHAN",
      doctor: "doc-diwakar",
      service: "AMSK",
      startTime: "15:00",
      endTime: "16:00",
      timeLabel: "3:00 PM – 4:00 PM",
      status: "booked",
      notes: "Dry needling calf & hamstrings",
      packageRemaining: "4 of 10 sessions",
      phone: "+91 97690 11223"
    },
    {
      id: "apt-206",
      patientId: "p-015",
      patientName: "BHASKAR SHETTY",
      doctor: "doc-diwakar",
      service: "AMSK",
      startTime: "16:00",
      endTime: "17:00",
      timeLabel: "4:00 PM – 5:00 PM",
      status: "booked",
      notes: "Chronic neck pain with tension headaches",
      packageRemaining: "8 of 10 sessions",
      phone: "+91 98204 99001"
    },
    {
      id: "apt-207",
      patientId: "p-016",
      patientName: "RUSHABH GANDHI",
      doctor: "doc-diwakar",
      service: "AMSK",
      startTime: "17:00",
      endTime: "18:00",
      timeLabel: "5:00 PM – 6:00 PM",
      status: "booked",
      notes: "Post workout impingement",
      packageRemaining: "3 of 5 sessions",
      phone: "+91 99300 22334"
    },
    {
      id: "apt-208",
      patientId: "p-017",
      patientName: "JULIAN SHAH",
      doctor: "doc-diwakar",
      service: "AMSK",
      startTime: "18:00",
      endTime: "19:00",
      timeLabel: "6:00 PM – 7:00 PM",
      status: "booked",
      notes: "Dr Shifa laser prior at 5:30",
      packageRemaining: "10 of 12 sessions",
      phone: "+91 98211 66778"
    },

    // --- Dr. Krishna Katkar ---
    {
      id: "apt-301",
      patientId: "p-018",
      patientName: "BOBBY BROOS",
      doctor: "doc-krishna",
      service: "AMSK",
      startTime: "09:30",
      endTime: "10:30",
      timeLabel: "9:30 AM – 10:30 AM",
      status: "ready",
      notes: "VIP patient - comprehensive spine adjustment",
      packageRemaining: "12 of 15 sessions",
      phone: "+91 98200 99887"
    },
    {
      id: "apt-302",
      patientId: "p-019",
      patientName: "POOJA BHANDARY",
      doctor: "doc-krishna",
      service: "AMSK",
      startTime: "10:30",
      endTime: "11:30",
      timeLabel: "10:30 AM – 11:30 AM",
      status: "in_progress",
      notes: "Cervical spondylosis",
      packageRemaining: "4 of 8 sessions",
      phone: "+91 98195 44332"
    },
    {
      id: "apt-303",
      patientId: "p-020",
      patientName: "INDUBEN TANK",
      doctor: "doc-krishna",
      service: "AMSK",
      startTime: "11:30",
      endTime: "12:30",
      timeLabel: "11:30 AM – 12:30 PM",
      status: "ready",
      notes: "Knee rehab and gait correction",
      packageRemaining: "6 of 10 sessions",
      phone: "+91 97691 22334"
    },
    {
      id: "apt-304",
      patientId: "p-021",
      patientName: "PINKY GADIA",
      doctor: "doc-krishna",
      service: "AMSK",
      startTime: "12:30",
      endTime: "13:30",
      timeLabel: "12:30 PM – 1:30 PM",
      status: "booked",
      notes: "Lumbar mobilization",
      packageRemaining: "2 of 6 sessions",
      phone: "+91 98203 11229"
    },
    {
      id: "apt-305",
      patientId: "p-022",
      patientName: "APEKSHA GADIA",
      doctor: "doc-krishna",
      service: "AMSK",
      startTime: "14:00",
      endTime: "15:00",
      timeLabel: "2:00 PM – 3:00 PM",
      status: "booked",
      notes: "Postural re-education",
      packageRemaining: "7 of 10 sessions",
      phone: "+91 99204 88776"
    },
    {
      id: "apt-306",
      patientId: "p-023",
      patientName: "FARAH DARUWALLA",
      doctor: "doc-krishna",
      service: "AMSK",
      startTime: "15:00",
      endTime: "16:00",
      timeLabel: "3:00 PM – 4:00 PM",
      status: "booked",
      notes: "SI joint dysfunction",
      packageRemaining: "5 of 10 sessions",
      phone: "+91 98339 55443"
    },
    {
      id: "apt-307",
      patientId: "p-024",
      patientName: "MARISSA MANSUKHANI",
      doctor: "doc-krishna",
      service: "AMSK",
      startTime: "16:00",
      endTime: "17:00",
      timeLabel: "4:00 PM – 5:00 PM",
      status: "absent",
      notes: "No Show reported at 3:45 PM",
      packageRemaining: "4 of 10 sessions",
      phone: "+91 98198 33221"
    },
    {
      id: "apt-308",
      patientId: "p-025",
      patientName: "KOMAL GULANI",
      doctor: "doc-krishna",
      service: "AMSK",
      startTime: "17:00",
      endTime: "18:00",
      timeLabel: "5:00 PM – 6:00 PM",
      status: "booked",
      notes: "Sciatica left leg",
      packageRemaining: "3 of 8 sessions",
      phone: "+91 97682 99881"
    },

    // --- Dr. Saurambika Shukla (AMSK & Women's Health) ---
    {
      id: "apt-401",
      patientId: "p-026",
      patientName: "BINITA PAREKH",
      doctor: "doc-saurambika",
      service: "AMSK",
      startTime: "11:30",
      endTime: "12:30",
      timeLabel: "11:30 AM – 12:30 PM",
      status: "booked",
      notes: "Post-natal pelvic rehab",
      packageRemaining: "6 of 10 sessions",
      phone: "+91 98208 77665"
    },
    {
      id: "apt-402",
      patientId: "p-027",
      patientName: "PRIYA SHINDE",
      doctor: "doc-saurambika",
      service: "AMSK",
      startTime: "12:30",
      endTime: "13:30",
      timeLabel: "12:30 PM – 1:30 PM",
      status: "booked",
      notes: "Shoulder impingement PT",
      packageRemaining: "4 of 6 sessions",
      phone: "+91 99301 44332"
    },
    {
      id: "apt-403",
      patientId: "p-028",
      patientName: "ANUPAM SEHGAL",
      doctor: "doc-saurambika",
      service: "AMSK",
      startTime: "14:00",
      endTime: "15:00",
      timeLabel: "2:00 PM – 3:00 PM",
      status: "booked",
      notes: "Thoracic outlet syndrome",
      packageRemaining: "8 of 10 sessions",
      phone: "+91 98197 66554"
    },
    {
      id: "apt-404",
      patientId: "p-029",
      patientName: "BINDI SHAH",
      doctor: "doc-saurambika",
      service: "AMSK",
      startTime: "15:00",
      endTime: "16:00",
      timeLabel: "3:00 PM – 4:00 PM",
      status: "booked",
      notes: "PARAS GOSAR SPINE D AT 3PM cross-ref",
      packageRemaining: "5 of 12 sessions",
      phone: "+91 98202 33445"
    },
    {
      id: "apt-405",
      patientId: "p-030",
      patientName: "PARIZAD DIVENTRI",
      doctor: "doc-saurambika",
      service: "AMSK",
      startTime: "16:00",
      endTime: "17:00",
      timeLabel: "4:00 PM – 5:00 PM",
      status: "booked",
      notes: "Lumbar stabilization",
      packageRemaining: "7 of 10 sessions",
      phone: "+91 97699 88776"
    },
    {
      id: "apt-406",
      patientId: "p-031",
      patientName: "STEVE VAZ",
      doctor: "doc-saurambika",
      service: "AMSK",
      startTime: "17:00",
      endTime: "18:00",
      timeLabel: "5:00 PM – 6:00 PM",
      status: "booked",
      notes: "Achilles tendonitis rehab",
      packageRemaining: "2 of 6 sessions",
      phone: "+91 98335 11990"
    },
    {
      id: "apt-407",
      patientId: "p-032",
      patientName: "STANLEY MONTEIRO",
      doctor: "doc-saurambika",
      service: "AMSK",
      startTime: "18:00",
      endTime: "19:00",
      timeLabel: "6:00 PM – 7:00 PM",
      status: "booked",
      notes: "Spine decompression followup",
      packageRemaining: "4 of 10 sessions",
      phone: "+91 98214 55667"
    },
    {
      id: "apt-408",
      patientId: "p-033",
      patientName: "JAVED KAZI",
      doctor: "doc-saurambika",
      service: "AMSK",
      startTime: "19:00",
      endTime: "20:00",
      timeLabel: "7:00 PM – 8:00 PM",
      status: "booked",
      notes: "Call Sweeta Parera if cancellation",
      packageRemaining: "9 of 10 sessions",
      phone: "+91 98196 22114"
    },

    // --- Dr. Hardi Mehta (AMSK) ---
    {
      id: "apt-501",
      patientId: "p-034",
      patientName: "RASHMI CHAUHAN",
      doctor: "doc-hardi",
      service: "AMSK",
      startTime: "12:30",
      endTime: "13:30",
      timeLabel: "12:30 PM – 1:30 PM",
      status: "booked",
      notes: "Knee rehab",
      packageRemaining: "5 of 10 sessions",
      phone: "+91 98207 44332"
    },
    {
      id: "apt-502",
      patientId: "p-035",
      patientName: "ASHOK JAIN",
      doctor: "doc-hardi",
      service: "AMSK",
      startTime: "14:00",
      endTime: "15:00",
      timeLabel: "2:00 PM – 3:00 PM",
      status: "booked",
      notes: "Thoracic alignment",
      packageRemaining: "3 of 6 sessions",
      phone: "+91 99209 88112"
    },
    {
      id: "apt-503",
      patientId: "p-036",
      patientName: "RADHIKA KHANDELWAL",
      doctor: "doc-hardi",
      service: "AMSK",
      startTime: "15:00",
      endTime: "16:00",
      timeLabel: "3:00 PM – 4:00 PM",
      status: "booked",
      notes: "Cervical collar weaning",
      packageRemaining: "6 of 10 sessions",
      phone: "+91 98194 55443"
    },
    {
      id: "apt-504",
      patientId: "p-037",
      patientName: "VINOD SEMELETY",
      doctor: "doc-hardi",
      service: "AMSK",
      startTime: "16:00",
      endTime: "17:00",
      timeLabel: "4:00 PM – 5:00 PM",
      status: "booked",
      notes: "Knee meniscus rehab",
      packageRemaining: "8 of 10 sessions",
      phone: "+91 98330 99887"
    },
    {
      id: "apt-505",
      patientId: "p-038",
      patientName: "ALPANA RODRIGES",
      doctor: "doc-hardi",
      service: "AMSK",
      startTime: "17:00",
      endTime: "18:00",
      timeLabel: "5:00 PM – 6:00 PM",
      status: "booked",
      notes: "Ankle sprain grade 2 recovery",
      packageRemaining: "4 of 8 sessions",
      phone: "+91 97697 11224"
    },
    {
      id: "apt-506",
      patientId: "p-039",
      patientName: "PRADEEP CHHABRIA",
      doctor: "doc-hardi",
      service: "AMSK",
      startTime: "18:00",
      endTime: "19:00",
      timeLabel: "6:00 PM – 7:00 PM",
      status: "booked",
      notes: "Lumbar extension exercises",
      packageRemaining: "7 of 10 sessions",
      phone: "+91 99308 66775"
    },
    {
      id: "apt-507",
      patientId: "p-040",
      patientName: "RAMESH SHRIVASTAVA",
      doctor: "doc-hardi",
      service: "AMSK",
      startTime: "19:00",
      endTime: "20:00",
      timeLabel: "7:00 PM – 8:00 PM",
      status: "booked",
      notes: "Followed by Cryo",
      packageRemaining: "6 of 10 sessions",
      phone: "+91 98206 33441"
    },

    // --- Dr. Spoorthi Poojary (AMSK) ---
    {
      id: "apt-601",
      patientId: "p-041",
      patientName: "BHAVNA VORA",
      doctor: "doc-spoorthi",
      service: "AMSK",
      startTime: "11:30",
      endTime: "12:30",
      timeLabel: "11:30 AM – 12:30 PM",
      status: "in_progress",
      notes: "Call Pooja Taktani if cancellation",
      packageRemaining: "5 of 10 sessions",
      phone: "+91 98207 44332"
    },
    {
      id: "apt-602",
      patientId: "p-042",
      patientName: "SWAPNA PATIL",
      doctor: "doc-spoorthi",
      service: "AMSK",
      startTime: "12:30",
      endTime: "13:30",
      timeLabel: "12:30 PM – 1:30 PM",
      status: "booked",
      notes: "Dint pick, confirmed on SMS",
      packageRemaining: "4 of 8 sessions",
      phone: "+91 99209 88112"
    },
    {
      id: "apt-603",
      patientId: "p-043",
      patientName: "DARSHANA JAIN",
      doctor: "doc-spoorthi",
      service: "AMSK",
      startTime: "14:00",
      endTime: "15:00",
      timeLabel: "2:00 PM – 3:00 PM",
      status: "booked",
      notes: "Followed by Magneto at 3:00 PM",
      packageRemaining: "9 of 10 sessions",
      phone: "+91 98193 44556"
    },
    {
      id: "apt-604",
      patientId: "p-044",
      patientName: "BINDI SHAH",
      doctor: "doc-spoorthi",
      service: "AMSK",
      startTime: "15:00",
      endTime: "16:00",
      timeLabel: "3:00 PM – 4:00 PM",
      status: "booked",
      notes: "PARAS GOSAR SPINE D AT 3PM cross-ref",
      packageRemaining: "3 of 5 sessions",
      phone: "+91 98202 33445"
    },
    {
      id: "apt-605",
      patientId: "p-045",
      patientName: "SAKSHI RANE",
      doctor: "doc-spoorthi",
      service: "AMSK",
      startTime: "16:00",
      endTime: "17:00",
      timeLabel: "4:00 PM – 5:00 PM",
      status: "booked",
      notes: "Spine Decompression combination",
      packageRemaining: "5 of 10 sessions",
      phone: "+91 98209 66554"
    },
    {
      id: "apt-606",
      patientId: "p-046",
      patientName: "MONA ALVI",
      doctor: "doc-spoorthi",
      service: "AMSK",
      startTime: "17:00",
      endTime: "18:00",
      timeLabel: "5:00 PM – 6:00 PM",
      status: "booked",
      notes: "Neck spasm dry needling",
      packageRemaining: "2 of 6 sessions",
      phone: "+91 98194 33221"
    },
    {
      id: "apt-607",
      patientId: "p-047",
      patientName: "MUKESH MAKWANA",
      doctor: "doc-spoorthi",
      service: "AMSK",
      startTime: "18:00",
      endTime: "19:00",
      timeLabel: "6:00 PM – 7:00 PM",
      status: "booked",
      notes: "No show reported",
      packageRemaining: "8 of 10 sessions",
      phone: "+91 97697 11445"
    },
    {
      id: "apt-608",
      patientId: "p-048",
      patientName: "PRANAY NAWLAKHA",
      doctor: "doc-spoorthi",
      service: "AMSK",
      startTime: "19:00",
      endTime: "20:00",
      timeLabel: "7:00 PM – 8:00 PM",
      status: "booked",
      notes: "Thoracic spine mobilization",
      packageRemaining: "6 of 8 sessions",
      phone: "+91 98336 99001"
    },

    // --- Dr. Shifa Sayyed (THOR Laser & Spine D) ---
    {
      id: "apt-701",
      patientId: "p-046",
      patientName: "MAMTA OBHAN",
      doctor: "doc-shifa",
      service: "THOR",
      startTime: "13:00",
      endTime: "13:30",
      timeLabel: "1:00 PM – 1:30 PM",
      status: "booked",
      notes: "THOR laser knee trigger points",
      packageRemaining: "4 of 10 sessions",
      phone: "+91 98206 55443"
    },
    {
      id: "apt-702",
      patientId: "p-047",
      patientName: "KUMKUM MEHTA",
      doctor: "doc-shifa",
      service: "THOR",
      startTime: "14:30",
      endTime: "15:00",
      timeLabel: "2:30 PM – 3:00 PM",
      status: "booked",
      notes: "Give invoice after session",
      packageRemaining: "7 of 10 sessions",
      phone: "+91 99208 33221"
    },
    {
      id: "apt-703",
      patientId: "p-048",
      patientName: "SANJALI GUPTE",
      doctor: "doc-shifa",
      service: "THOR",
      startTime: "15:00",
      endTime: "15:30",
      timeLabel: "3:00 PM – 3:30 PM",
      status: "booked",
      notes: "Laser wrist tenosynovitis",
      packageRemaining: "5 of 6 sessions",
      phone: "+91 97685 11990"
    },
    {
      id: "apt-704",
      patientId: "p-049",
      patientName: "ARVIND RAVARIYA",
      doctor: "doc-shifa",
      service: "THOR",
      startTime: "16:00",
      endTime: "16:30",
      timeLabel: "4:00 PM – 4:30 PM",
      status: "booked",
      notes: "DR SHIFA ONLY - Lower back photobiomodulation",
      packageRemaining: "8 of 10 sessions",
      phone: "+91 98193 88776"
    },
    {
      id: "apt-705",
      patientId: "p-050",
      patientName: "RUSHABH GANDHI",
      doctor: "doc-shifa",
      service: "THOR",
      startTime: "16:30",
      endTime: "17:00",
      timeLabel: "4:30 PM – 5:00 PM",
      status: "booked",
      notes: "Combined with AMSK at 5PM",
      packageRemaining: "3 of 5 sessions",
      phone: "+91 99300 22334"
    },
    {
      id: "apt-706",
      patientId: "p-051",
      patientName: "SAKINA MERCHANT",
      doctor: "doc-shifa",
      service: "THOR",
      startTime: "17:00",
      endTime: "17:30",
      timeLabel: "5:00 PM – 5:30 PM",
      status: "booked",
      notes: "Cervical laser protocol",
      packageRemaining: "6 of 10 sessions",
      phone: "+91 98217 66554"
    },
    {
      id: "apt-707",
      patientId: "p-052",
      patientName: "BINDU NAVEEN",
      doctor: "doc-shifa",
      service: "THOR",
      startTime: "18:30",
      endTime: "19:00",
      timeLabel: "6:30 PM – 7:00 PM",
      status: "booked",
      notes: "Shoulder tendonitis laser",
      packageRemaining: "9 of 10 sessions",
      phone: "+91 98338 44332"
    },
    {
      id: "apt-708",
      patientId: "p-053",
      patientName: "ALI AKBAR LAKHANI",
      doctor: "doc-shifa",
      service: "THOR",
      startTime: "19:00",
      endTime: "19:30",
      timeLabel: "7:00 PM – 7:30 PM",
      status: "absent",
      notes: "No show recorded at 7:15 PM",
      packageRemaining: "2 of 6 sessions",
      phone: "+91 97692 77881"
    },
    {
      id: "apt-709",
      patientId: "p-054",
      patientName: "JASMINE SINGLE",
      doctor: "doc-shifa",
      service: "THOR",
      startTime: "19:30",
      endTime: "20:00",
      timeLabel: "7:30 PM – 8:00 PM",
      status: "booked",
      notes: "DR SHIFA ONLY",
      packageRemaining: "5 of 8 sessions",
      phone: "+91 98201 11335"
    },

    // --- Dr. Anjali Dalwadi (DTT / ACW / HBOT) ---
    {
      id: "apt-801",
      patientId: "p-055",
      patientName: "BASANTI JAIN",
      doctor: "doc-anjali",
      service: "DTT",
      startTime: "09:00",
      endTime: "09:30",
      timeLabel: "9:00 AM – 9:30 AM",
      status: "ready",
      notes: "Cervical DTT before physio",
      packageRemaining: "6 of 10 sessions",
      phone: "+91 98201 44521"
    },
    {
      id: "apt-802",
      patientId: "p-056",
      patientName: "RAZIA HAMA",
      doctor: "doc-anjali",
      service: "DTT",
      startTime: "09:30",
      endTime: "10:00",
      timeLabel: "9:30 AM – 10:00 AM",
      status: "booked",
      notes: "Upper back stiffness DTT",
      packageRemaining: "3 of 5 sessions",
      phone: "+91 98196 00998"
    },
    {
      id: "apt-803",
      patientId: "p-057",
      patientName: "KULWANT DHAWAN",
      doctor: "doc-anjali",
      service: "DTT",
      startTime: "10:00",
      endTime: "10:30",
      timeLabel: "10:00 AM – 10:30 AM",
      status: "booked",
      notes: "Lumbar DTT",
      packageRemaining: "7 of 10 sessions",
      phone: "+91 99205 77665"
    },
    {
      id: "apt-804",
      patientId: "p-058",
      patientName: "MADHAVI KADAM",
      doctor: "doc-anjali",
      service: "DTT",
      startTime: "12:00",
      endTime: "12:30",
      timeLabel: "12:00 PM – 12:30 PM",
      status: "ready",
      notes: "Shoulder DTT",
      packageRemaining: "4 of 8 sessions",
      phone: "+91 97698 22119"
    },
    {
      id: "apt-805",
      patientId: "p-059",
      patientName: "MAMTA ASHAR",
      doctor: "doc-anjali",
      service: "DTT",
      startTime: "14:30",
      endTime: "15:00",
      timeLabel: "2:30 PM – 3:00 PM",
      status: "booked",
      notes: "Give invoice",
      packageRemaining: "5 of 10 sessions",
      phone: "+91 98337 22119"
    },
    {
      id: "apt-806",
      patientId: "p-060",
      patientName: "JIGNA MEHTA",
      doctor: "doc-anjali",
      service: "DTT",
      startTime: "15:00",
      endTime: "15:30",
      timeLabel: "3:00 PM – 3:30 PM",
      status: "booked",
      notes: "Payment confirmed",
      packageRemaining: "8 of 10 sessions",
      phone: "+91 98212 88776"
    },
    {
      id: "apt-807",
      patientId: "p-061",
      patientName: "AASHISH PATIL",
      doctor: "doc-anjali",
      service: "DTT",
      startTime: "17:00",
      endTime: "17:30",
      timeLabel: "5:00 PM – 5:30 PM",
      status: "booked",
      notes: "Bilateral calves DTT",
      packageRemaining: "2 of 6 sessions",
      phone: "+91 98199 44556"
    },
    {
      id: "apt-808",
      patientId: "p-062",
      patientName: "STANLEY MONTEIRO",
      doctor: "doc-anjali",
      service: "DTT",
      startTime: "17:30",
      endTime: "18:00",
      timeLabel: "5:30 PM – 6:00 PM",
      status: "booked",
      notes: "Prior to AMSK",
      packageRemaining: "4 of 10 sessions",
      phone: "+91 98214 55667"
    },

    // --- Dr. Abhipsha Majumder (AMSK / THOR / MAGNETO) ---
    {
      id: "apt-901",
      patientId: "p-063",
      patientName: "FATIMA QURESHI",
      doctor: "doc-abhipsha",
      service: "THOR",
      startTime: "10:30",
      endTime: "11:00",
      timeLabel: "10:30 AM – 11:00 AM",
      status: "booked",
      notes: "DR KHUSHBOO cross referral",
      packageRemaining: "6 of 10 sessions",
      phone: "+91 99302 99881"
    },
    {
      id: "apt-902",
      patientId: "p-064",
      patientName: "NAMRATA RAKHECHA",
      doctor: "doc-abhipsha",
      service: "THOR",
      startTime: "11:00",
      endTime: "11:30",
      timeLabel: "11:00 AM – 11:30 AM",
      status: "cancelled",
      notes: "Cancelled & rescheduled to Friday",
      packageRemaining: "7 of 10 sessions",
      phone: "+91 97683 44552"
    },
    {
      id: "apt-903",
      patientId: "p-065",
      patientName: "NIKITA JAIN",
      doctor: "doc-abhipsha",
      service: "THOR",
      startTime: "11:30",
      endTime: "12:00",
      timeLabel: "11:30 AM – 12:00 PM",
      status: "booked",
      notes: "Laser lumbar facet joints",
      packageRemaining: "4 of 8 sessions",
      phone: "+91 98205 11993"
    },
    {
      id: "apt-904",
      patientId: "p-066",
      patientName: "JUNAID SHAIKH",
      doctor: "doc-abhipsha",
      service: "THOR",
      startTime: "13:30",
      endTime: "14:00",
      timeLabel: "1:30 PM – 2:00 PM",
      status: "booked",
      notes: "DR ABHIPSHA ONLY",
      packageRemaining: "8 of 10 sessions",
      phone: "+91 98197 33445"
    },
    {
      id: "apt-905",
      patientId: "p-067",
      patientName: "ASHOK JAIN",
      doctor: "doc-abhipsha",
      service: "MAGNETO",
      startTime: "15:00",
      endTime: "15:30",
      timeLabel: "3:00 PM – 3:30 PM",
      status: "booked",
      notes: "PEMF therapy knee",
      packageRemaining: "5 of 10 sessions",
      phone: "+91 99207 00112"
    },
    {
      id: "apt-906",
      patientId: "p-068",
      patientName: "BABU BASHIR SHAIKH",
      doctor: "doc-abhipsha",
      service: "MAGNETO",
      startTime: "16:00",
      endTime: "16:30",
      timeLabel: "4:00 PM – 4:30 PM",
      status: "booked",
      notes: "DR SHIFA ONLY co-managed",
      packageRemaining: "3 of 6 sessions",
      phone: "+91 97690 99887"
    },
    {
      id: "apt-907",
      patientId: "p-069",
      patientName: "SAKINA MERCHANT",
      doctor: "doc-abhipsha",
      service: "MAGNETO",
      startTime: "17:00",
      endTime: "17:30",
      timeLabel: "5:00 PM – 5:30 PM",
      status: "booked",
      notes: "PEMF cervical",
      packageRemaining: "6 of 10 sessions",
      phone: "+91 98217 66554"
    },
    {
      id: "apt-908",
      patientId: "p-070",
      patientName: "UDIT GADIA",
      doctor: "doc-abhipsha",
      service: "MAGNETO",
      startTime: "18:00",
      endTime: "18:30",
      timeLabel: "6:00 PM – 6:30 PM",
      status: "booked",
      notes: "Payment confirmed",
      packageRemaining: "9 of 10 sessions",
      phone: "+91 98332 55441"
    },

    // --- Dr. Sakshi Bhardwaj (DTT, ACW, Cryo, Red Light) ---
    {
      id: "apt-1101",
      patientId: "p-077",
      patientName: "AMMAR PATANWALA",
      doctor: "doc-sakshi-b",
      service: "DTT",
      startTime: "09:00",
      endTime: "09:30",
      timeLabel: "9:00 AM – 9:30 AM",
      status: "ready",
      notes: "Cervical stiffness DTT",
      packageRemaining: "5 of 10 sessions",
      phone: "+91 98205 88990"
    },
    {
      id: "apt-1102",
      patientId: "p-078",
      patientName: "ANITA R JAIN",
      doctor: "doc-sakshi-b",
      service: "DTT",
      startTime: "10:30",
      endTime: "11:00",
      timeLabel: "10:30 AM – 11:00 AM",
      status: "booked",
      notes: "Shoulder DTT protocol",
      packageRemaining: "3 of 6 sessions",
      phone: "+91 99203 77441"
    },
    {
      id: "apt-1103",
      patientId: "p-079",
      patientName: "MEREENA DESOUZA",
      doctor: "doc-sakshi-b",
      service: "DTT",
      startTime: "11:30",
      endTime: "12:00",
      timeLabel: "11:30 AM – 12:00 PM",
      status: "booked",
      notes: "Thoracic myofascial release",
      packageRemaining: "4 of 10 sessions",
      phone: "+91 98334 55102"
    },
    {
      id: "apt-1104",
      patientId: "p-080",
      patientName: "ROZMIN BABVANI",
      doctor: "doc-sakshi-b",
      service: "ACW",
      startTime: "12:00",
      endTime: "12:30",
      timeLabel: "12:00 PM – 12:30 PM",
      status: "booked",
      notes: "Acoustic wave knee tendinopathy",
      packageRemaining: "6 of 8 sessions",
      phone: "+91 98194 00112"
    },
    {
      id: "apt-1105",
      patientId: "p-081",
      patientName: "CHRISTOPHER DSOUZA",
      doctor: "doc-sakshi-b",
      service: "ACW",
      startTime: "12:30",
      endTime: "13:00",
      timeLabel: "12:30 PM – 1:00 PM",
      status: "booked",
      notes: "Plantar fasciitis shockwave",
      packageRemaining: "2 of 5 sessions",
      phone: "+91 97690 33445"
    },
    {
      id: "apt-1106",
      patientId: "p-082",
      patientName: "VATSAL SHAH",
      doctor: "doc-sakshi-b",
      service: "DTT",
      startTime: "13:00",
      endTime: "13:30",
      timeLabel: "1:00 PM – 1:30 PM",
      status: "booked",
      notes: "Low back DTT",
      packageRemaining: "8 of 10 sessions",
      phone: "+91 98218 55667"
    },
    {
      id: "apt-1107",
      patientId: "p-083",
      patientName: "LAURIANA FERNANDES",
      doctor: "doc-sakshi-b",
      service: "DTT",
      startTime: "15:00",
      endTime: "15:30",
      timeLabel: "3:00 PM – 3:30 PM",
      status: "booked",
      notes: "Cervical DTT",
      packageRemaining: "5 of 10 sessions",
      phone: "+91 98331 77889"
    },
    {
      id: "apt-1108",
      patientId: "p-084",
      patientName: "RADHIKA KHANDELWAL",
      doctor: "doc-sakshi-b",
      service: "DTT",
      startTime: "16:00",
      endTime: "16:30",
      timeLabel: "4:00 PM – 4:30 PM",
      status: "booked",
      notes: "Upper trapezius release",
      packageRemaining: "7 of 10 sessions",
      phone: "+91 99206 11223"
    },
    {
      id: "apt-1109",
      patientId: "p-085",
      patientName: "BHAVIN JAIN",
      doctor: "doc-sakshi-b",
      service: "DTT",
      startTime: "16:30",
      endTime: "17:00",
      timeLabel: "4:30 PM – 5:00 PM",
      status: "booked",
      notes: "Hamstrings DTT",
      packageRemaining: "3 of 6 sessions",
      phone: "+91 98197 44556"
    },
    {
      id: "apt-1110",
      patientId: "p-086",
      patientName: "ASIYA KAZI",
      doctor: "doc-sakshi-b",
      service: "DTT",
      startTime: "17:30",
      endTime: "18:00",
      timeLabel: "5:30 PM – 6:00 PM",
      status: "booked",
      notes: "Payment confirmed",
      packageRemaining: "9 of 10 sessions",
      phone: "+91 97689 00998"
    },

    // --- Dr. Sakshi Singh (Class 4 HIL & Robotic Spine) ---
    {
      id: "apt-1201",
      patientId: "p-087",
      patientName: "JAIRAM PAWAR",
      doctor: "doc-sakshi-s",
      service: "HIL",
      startTime: "09:30",
      endTime: "10:00",
      timeLabel: "9:30 AM – 10:00 AM",
      status: "ready",
      notes: "Class 4 Laser lumbar L5-S1",
      packageRemaining: "4 of 10 sessions",
      phone: "+91 98203 44556"
    },
    {
      id: "apt-1202",
      patientId: "p-088",
      patientName: "FLORINE SARKAR",
      doctor: "doc-sakshi-s",
      service: "HIL",
      startTime: "10:30",
      endTime: "11:00",
      timeLabel: "10:30 AM – 11:00 AM",
      status: "booked",
      notes: "High intensity laser knee",
      packageRemaining: "7 of 10 sessions",
      phone: "+91 99209 11223"
    },
    {
      id: "apt-1203",
      patientId: "p-089",
      patientName: "TALATH MUJEEB HAWA",
      doctor: "doc-sakshi-s",
      service: "HIL",
      startTime: "11:00",
      endTime: "11:30",
      timeLabel: "11:00 AM – 11:30 AM",
      status: "booked",
      notes: "Laser cervical spine",
      packageRemaining: "5 of 8 sessions",
      phone: "+91 98190 66778"
    },
    {
      id: "apt-1204",
      patientId: "p-090",
      patientName: "GIRISH PATEL",
      doctor: "doc-sakshi-s",
      service: "RBA",
      startTime: "11:30",
      endTime: "12:00",
      timeLabel: "11:30 AM – 12:00 PM",
      status: "booked",
      notes: "Robotic spine aligner mobilization",
      packageRemaining: "6 of 10 sessions",
      phone: "+91 97693 88990"
    },
    {
      id: "apt-1205",
      patientId: "p-091",
      patientName: "SONU JAIN",
      doctor: "doc-sakshi-s",
      service: "RBA",
      startTime: "12:00",
      endTime: "12:30",
      timeLabel: "12:00 PM – 12:30 PM",
      status: "booked",
      notes: "Robotic alignment session 4",
      packageRemaining: "4 of 10 sessions",
      phone: "+91 98335 22114"
    },
    {
      id: "apt-1206",
      patientId: "p-092",
      patientName: "SHREEYA KOKATE",
      doctor: "doc-sakshi-s",
      service: "HIL",
      startTime: "13:00",
      endTime: "13:30",
      timeLabel: "1:00 PM – 1:30 PM",
      status: "booked",
      notes: "DR SAKSHI S ONLY",
      packageRemaining: "8 of 10 sessions",
      phone: "+91 98212 99001"
    },
    {
      id: "apt-1207",
      patientId: "p-093",
      patientName: "NIVIKA PRADHAN",
      doctor: "doc-sakshi-s",
      service: "HIL",
      startTime: "15:00",
      endTime: "15:30",
      timeLabel: "3:00 PM – 3:30 PM",
      status: "booked",
      notes: "High intensity laser ankle",
      packageRemaining: "3 of 6 sessions",
      phone: "+91 98195 77665"
    },
    {
      id: "apt-1208",
      patientId: "p-094",
      patientName: "UJJWALA JADHAV",
      doctor: "doc-sakshi-s",
      service: "RBA",
      startTime: "16:00",
      endTime: "16:30",
      timeLabel: "4:00 PM – 4:30 PM",
      status: "booked",
      notes: "Spine robotic alignment",
      packageRemaining: "7 of 10 sessions",
      phone: "+91 99202 44332"
    },
    {
      id: "apt-1209",
      patientId: "p-095",
      patientName: "SHWETA TALWAR",
      doctor: "doc-sakshi-s",
      service: "HIL",
      startTime: "16:30",
      endTime: "17:00",
      timeLabel: "4:30 PM – 5:00 PM",
      status: "booked",
      notes: "Shoulder HIL",
      packageRemaining: "5 of 10 sessions",
      phone: "+91 98207 11990"
    },
    {
      id: "apt-1210",
      patientId: "p-096",
      patientName: "RAJIV MANEK",
      doctor: "doc-sakshi-s",
      service: "RBA",
      startTime: "17:00",
      endTime: "17:30",
      timeLabel: "5:00 PM – 5:30 PM",
      status: "booked",
      notes: "Robotic spine decompression alignment",
      packageRemaining: "9 of 10 sessions",
      phone: "+91 97691 55443"
    },

    // --- Specialized Pods: HBOT / Ice Bath / Red Light ---
    {
      id: "apt-1301",
      patientId: "p-097",
      patientName: "BASANTI JAIN",
      doctor: "doc-anjali",
      service: "HBOT_HARD",
      startTime: "09:00",
      endTime: "10:00",
      timeLabel: "9:00 AM – 10:00 AM",
      status: "ready",
      notes: "Hard chamber 2.0 ATA oxygen session",
      packageRemaining: "6 of 10 sessions",
      phone: "+91 98201 44521"
    },
    {
      id: "apt-1302",
      patientId: "p-098",
      patientName: "ANITA R JAIN",
      doctor: "doc-hardi",
      service: "HBOT_SOFT",
      startTime: "10:00",
      endTime: "11:00",
      timeLabel: "10:00 AM – 11:00 AM",
      status: "booked",
      notes: "Soft chamber 1.3 ATA oxygen session",
      packageRemaining: "3 of 6 sessions",
      phone: "+91 99203 77441"
    },
    {
      id: "apt-1303",
      patientId: "p-099",
      patientName: "SWAPNA PATIL",
      doctor: "doc-anjali",
      service: "RED_LIGHT",
      startTime: "12:00",
      endTime: "12:30",
      timeLabel: "12:00 PM – 12:30 PM",
      status: "booked",
      notes: "Full body red light phototherapy bed",
      packageRemaining: "5 of 10 sessions",
      phone: "+91 99209 88112"
    },
    {
      id: "apt-1304",
      patientId: "p-100",
      patientName: "SHREEYA KOKATE",
      doctor: "doc-anjali",
      service: "RED_LIGHT",
      startTime: "12:30",
      endTime: "13:00",
      timeLabel: "12:30 PM – 1:00 PM",
      status: "booked",
      notes: "Red light cellular regeneration",
      packageRemaining: "8 of 10 sessions",
      phone: "+91 98212 99001"
    },
    {
      id: "apt-1305",
      patientId: "p-101",
      patientName: "AAMIR MANIAR",
      doctor: "doc-anjali",
      service: "ICE_BATH",
      startTime: "13:30",
      endTime: "14:00",
      timeLabel: "1:30 PM – 2:00 PM",
      status: "booked",
      notes: "Cold immersion 8°C recovery",
      packageRemaining: "4 of 8 sessions",
      phone: "+91 98198 22119"
    },
    {
      id: "apt-1306",
      patientId: "p-102",
      patientName: "DARSHANA JAIN",
      doctor: "doc-sakshi-b",
      service: "CRYOTHERAPY",
      startTime: "15:00",
      endTime: "15:30",
      timeLabel: "3:00 PM – 3:30 PM",
      status: "booked",
      notes: "-110°C whole body cryo chamber",
      packageRemaining: "6 of 10 sessions",
      phone: "+91 97694 55667"
    },
    {
      id: "apt-1307",
      patientId: "p-103",
      patientName: "SAKINA MERCHANT",
      doctor: "doc-anjali",
      service: "RED_LIGHT",
      startTime: "17:30",
      endTime: "18:00",
      timeLabel: "5:30 PM – 6:00 PM",
      status: "booked",
      notes: "Red light photo bed post laser",
      packageRemaining: "6 of 10 sessions",
      phone: "+91 98217 66554"
    },
    {
      id: "apt-1308",
      patientId: "p-104",
      patientName: "KAVITA JANGID",
      doctor: "doc-anjali",
      service: "ICE_BATH",
      startTime: "18:00",
      endTime: "18:30",
      timeLabel: "6:00 PM – 6:30 PM",
      status: "booked",
      notes: "Post workout cold therapy",
      packageRemaining: "2 of 5 sessions",
      phone: "+91 99208 44119"
    },

    // --- HBOT Hard Shell (doc-hbot-hard) --- 1 Hour sessions ---
    {
      id: "apt-1401",
      patientId: "p-009",
      patientName: "IQBAL SHAIKH",
      doctor: "doc-hbot-hard",
      service: "HBOT_HARD",
      startTime: "09:00",
      endTime: "10:00",
      timeLabel: "9:00 AM – 10:00 AM",
      status: "ready",
      notes: "HBOT Hard Shell 2.0 ATA — session 3 of 10",
      packageRemaining: "8 of 10 sessions",
      phone: "+91 97688 00192"
    },
    {
      id: "apt-1402",
      patientId: "p-010",
      patientName: "VIKRANT KAVITAKE",
      doctor: "doc-hbot-hard",
      service: "HBOT_HARD",
      startTime: "10:00",
      endTime: "11:00",
      timeLabel: "10:00 AM – 11:00 AM",
      status: "booked",
      notes: "Post-injury neuro recovery — HBOT 2.0 ATA",
      packageRemaining: "6 of 10 sessions",
      phone: "+91 98200 12399"
    },
    {
      id: "apt-1403",
      patientId: "p-011",
      patientName: "SUMIT PAKHALE",
      doctor: "doc-hbot-hard",
      service: "HBOT_HARD",
      startTime: "11:00",
      endTime: "12:00",
      timeLabel: "11:00 AM – 12:00 PM",
      status: "booked",
      notes: "Chronic fatigue — hard shell HBOT protocol",
      packageRemaining: "5 of 10 sessions",
      phone: "+91 99201 88472"
    },
    {
      id: "apt-1404",
      patientId: "p-012",
      patientName: "GOVIND KHETAN",
      doctor: "doc-hbot-hard",
      service: "HBOT_HARD",
      startTime: "12:00",
      endTime: "13:00",
      timeLabel: "12:00 PM – 1:00 PM",
      status: "booked",
      notes: "Wound healing HBOT — diabetic foot",
      packageRemaining: "3 of 10 sessions",
      phone: "+91 98331 44556"
    },
    {
      id: "apt-1405",
      patientId: "p-013",
      patientName: "BOBBY BROOS",
      doctor: "doc-hbot-hard",
      service: "HBOT_HARD",
      startTime: "14:00",
      endTime: "15:00",
      timeLabel: "2:00 PM – 3:00 PM",
      status: "booked",
      notes: "VIP elite recovery — hard shell protocol",
      packageRemaining: "7 of 10 sessions",
      phone: "+91 98200 99887"
    },
    {
      id: "apt-1406",
      patientId: "p-014",
      patientName: "POOJA BHANDARY",
      doctor: "doc-hbot-hard",
      service: "HBOT_HARD",
      startTime: "15:00",
      endTime: "16:00",
      timeLabel: "3:00 PM – 4:00 PM",
      status: "booked",
      notes: "Post-op tissue healing HBOT",
      packageRemaining: "4 of 8 sessions",
      phone: "+91 98195 44332"
    },
    {
      id: "apt-1407",
      patientId: "p-015",
      patientName: "BINITA PAREKH",
      doctor: "doc-hbot-hard",
      service: "HBOT_HARD",
      startTime: "16:00",
      endTime: "17:00",
      timeLabel: "4:00 PM – 5:00 PM",
      status: "booked",
      notes: "Anti-inflammatory hard HBOT",
      packageRemaining: "2 of 6 sessions",
      phone: "+91 98208 77665"
    },

    // --- HBOT Soft Shell (doc-hbot-soft) --- 1 Hour sessions ---
    {
      id: "apt-1501",
      patientId: "p-016",
      patientName: "MAMTA OBHAN",
      doctor: "doc-hbot-soft",
      service: "HBOT_SOFT",
      startTime: "10:00",
      endTime: "11:00",
      timeLabel: "10:00 AM – 11:00 AM",
      status: "ready",
      notes: "HBOT Soft 1.3 ATA — mild hyperbaric recovery",
      packageRemaining: "6 of 10 sessions",
      phone: "+91 98206 55443"
    },
    {
      id: "apt-1502",
      patientId: "p-017",
      patientName: "KUMKUM MEHTA",
      doctor: "doc-hbot-soft",
      service: "HBOT_SOFT",
      startTime: "11:00",
      endTime: "12:00",
      timeLabel: "11:00 AM – 12:00 PM",
      status: "booked",
      notes: "Systemic anti-inflammatory HBOT soft shell",
      packageRemaining: "4 of 8 sessions",
      phone: "+91 99208 33221"
    },
    {
      id: "apt-1503",
      patientId: "p-018",
      patientName: "FATIMA QURESHI",
      doctor: "doc-hbot-soft",
      service: "HBOT_SOFT",
      startTime: "12:00",
      endTime: "13:00",
      timeLabel: "12:00 PM – 1:00 PM",
      status: "in_progress",
      notes: "HBOT 1.5 ATA — fibromyalgia recovery",
      packageRemaining: "7 of 10 sessions",
      phone: "+91 99302 99881"
    },
    {
      id: "apt-1504",
      patientId: "p-019",
      patientName: "ARVIND RAVARIYA",
      doctor: "doc-hbot-soft",
      service: "HBOT_SOFT",
      startTime: "14:00",
      endTime: "15:00",
      timeLabel: "2:00 PM – 3:00 PM",
      status: "booked",
      notes: "Soft HBOT — immune boost protocol",
      packageRemaining: "3 of 10 sessions",
      phone: "+91 98193 88776"
    },
    {
      id: "apt-1505",
      patientId: "p-020",
      patientName: "JASMINE SINGLE",
      doctor: "doc-hbot-soft",
      service: "HBOT_SOFT",
      startTime: "15:00",
      endTime: "16:00",
      timeLabel: "3:00 PM – 4:00 PM",
      status: "booked",
      notes: "Long covid recovery — soft shell HBOT",
      packageRemaining: "8 of 10 sessions",
      phone: "+91 98201 11335"
    },
    {
      id: "apt-1506",
      patientId: "p-001",
      patientName: "BASANTI JAIN",
      doctor: "doc-hbot-soft",
      service: "HBOT_SOFT",
      startTime: "16:00",
      endTime: "17:00",
      timeLabel: "4:00 PM – 5:00 PM",
      status: "booked",
      notes: "Chronic pain systemic recovery HBOT",
      packageRemaining: "5 of 10 sessions",
      phone: "+91 98201 44521"
    },

    // --- Red Light Therapy (doc-red-foot) ---
    {
      id: "apt-1601",
      patientId: "p-002",
      patientName: "RUKHSHANA SHOLAPURWALA",
      doctor: "doc-red-foot",
      service: "RED_LIGHT",
      startTime: "09:00",
      endTime: "09:30",
      timeLabel: "9:00 AM – 9:30 AM",
      status: "ready",
      notes: "Full body red light phototherapy — skin and pain",
      packageRemaining: "4 of 10 sessions",
      phone: "+91 98192 11093"
    },
    {
      id: "apt-1602",
      patientId: "p-003",
      patientName: "RANI MHATRE",
      doctor: "doc-red-foot",
      service: "RED_LIGHT",
      startTime: "09:30",
      endTime: "10:00",
      timeLabel: "9:30 AM – 10:00 AM",
      status: "booked",
      notes: "NIR light — joint inflammation",
      packageRemaining: "6 of 10 sessions",
      phone: "+91 97693 88120"
    },
    {
      id: "apt-1603",
      patientId: "p-004",
      patientName: "DHARMISHTHA VORA",
      doctor: "doc-red-foot",
      service: "RED_LIGHT",
      startTime: "10:00",
      endTime: "10:30",
      timeLabel: "10:00 AM – 10:30 AM",
      status: "booked",
      notes: "Red light + NIR bed — post-surgery healing",
      packageRemaining: "8 of 10 sessions",
      phone: "+91 98210 99432"
    },
    {
      id: "apt-1604",
      patientId: "p-005",
      patientName: "MEREENA DESOUZA",
      doctor: "doc-red-foot",
      service: "RED_LIGHT",
      startTime: "11:00",
      endTime: "11:30",
      timeLabel: "11:00 AM – 11:30 AM",
      status: "booked",
      notes: "Chronic fatigue — red light mitochondria boost",
      packageRemaining: "3 of 8 sessions",
      phone: "+91 98334 55102"
    },
    {
      id: "apt-1605",
      patientId: "p-006",
      patientName: "SHEETAL SHAH",
      doctor: "doc-red-foot",
      service: "RED_LIGHT",
      startTime: "14:00",
      endTime: "14:30",
      timeLabel: "2:00 PM – 2:30 PM",
      status: "booked",
      notes: "Red light post DTT session",
      packageRemaining: "5 of 10 sessions",
      phone: "+91 99200 44321"
    },

    // --- Red Foot Insoles (doc-red-foot) ---
    {
      id: "apt-1701",
      patientId: "p-007",
      patientName: "SHASHIKALA VAIRAGAR",
      doctor: "doc-foot-insole",
      service: "RED_FOOT_INSOLES",
      startTime: "12:00",
      endTime: "12:30",
      timeLabel: "12:00 PM – 12:30 PM",
      status: "ready",
      notes: "Gait analysis + custom insole fitting session 1",
      packageRemaining: "1 of 3 sessions",
      phone: "+91 98205 66781"
    },
    {
      id: "apt-1702",
      patientId: "p-008",
      patientName: "DEEPA OBEROI",
      doctor: "doc-foot-insole",
      service: "RED_FOOT_INSOLES",
      startTime: "12:30",
      endTime: "13:00",
      timeLabel: "12:30 PM – 1:00 PM",
      status: "booked",
      notes: "Plantar fasciitis — red foot pressure map",
      packageRemaining: "2 of 3 sessions",
      phone: "+91 98199 22345"
    },
    {
      id: "apt-1703",
      patientId: "p-009",
      patientName: "IQBAL SHAIKH",
      doctor: "doc-foot-insole",
      service: "RED_FOOT_INSOLES",
      startTime: "15:00",
      endTime: "15:30",
      timeLabel: "3:00 PM – 3:30 PM",
      status: "booked",
      notes: "Follow-up insole adjustment",
      packageRemaining: "3 of 3 sessions",
      phone: "+91 97688 00192"
    },
    {
      id: "apt-1704",
      patientId: "p-010",
      patientName: "VIKRANT KAVITAKE",
      doctor: "doc-foot-insole",
      service: "RED_FOOT_INSOLES",
      startTime: "15:30",
      endTime: "16:00",
      timeLabel: "3:30 PM – 4:00 PM",
      status: "booked",
      notes: "Biomechanical correction — flat foot insoles",
      packageRemaining: "1 of 3 sessions",
      phone: "+91 98200 12399"
    },

    // --- Spine Decompression (doc-spine-d) ---
    {
      id: "apt-1801",
      patientId: "p-011",
      patientName: "SUMIT PAKHALE",
      doctor: "doc-spine-d",
      service: "SPINE_D",
      startTime: "09:30",
      endTime: "10:00",
      timeLabel: "9:30 AM – 10:00 AM",
      status: "ready",
      notes: "L4-L5 disc herniation — decompression session 5",
      packageRemaining: "5 of 10 sessions",
      phone: "+91 99201 88472"
    },
    {
      id: "apt-1802",
      patientId: "p-012",
      patientName: "GOVIND KHETAN",
      doctor: "doc-spine-d",
      service: "SPINE_D",
      startTime: "10:00",
      endTime: "10:30",
      timeLabel: "10:00 AM – 10:30 AM",
      status: "booked",
      notes: "Cervical disc bulge — traction protocol",
      packageRemaining: "3 of 8 sessions",
      phone: "+91 98331 44556"
    },
    {
      id: "apt-1803",
      patientId: "p-013",
      patientName: "BOBBY BROOS",
      doctor: "doc-spine-d",
      service: "SPINE_D",
      startTime: "11:00",
      endTime: "11:30",
      timeLabel: "11:00 AM – 11:30 AM",
      status: "booked",
      notes: "VIP — lumbar decompression spinal traction",
      packageRemaining: "7 of 10 sessions",
      phone: "+91 98200 99887"
    },
    {
      id: "apt-1804",
      patientId: "p-019",
      patientName: "ARVIND RAVARIYA",
      doctor: "doc-spine-d",
      service: "SPINE_D",
      startTime: "14:00",
      endTime: "14:30",
      timeLabel: "2:00 PM – 2:30 PM",
      status: "booked",
      notes: "Spondylolisthesis — spine decompression rehab",
      packageRemaining: "6 of 10 sessions",
      phone: "+91 98193 88776"
    },
    {
      id: "apt-1805",
      patientId: "p-020",
      patientName: "JASMINE SINGLE",
      doctor: "doc-spine-d",
      service: "SPINE_D",
      startTime: "15:00",
      endTime: "15:30",
      timeLabel: "3:00 PM – 3:30 PM",
      status: "booked",
      notes: "Sciatica — computerized lumbar traction",
      packageRemaining: "4 of 8 sessions",
      phone: "+91 98201 11335"
    },
    // --- Pelvic Chair (doc-pelvic-chair) ---
    {
      id: "apt-1901",
      patientId: "p-015",
      patientName: "BINITA PAREKH",
      doctor: "doc-pelvic-chair",
      service: "PELVIC_CHAIR",
      startTime: "11:00",
      endTime: "11:30",
      timeLabel: "11:00 AM – 11:30 AM",
      status: "ready",
      notes: "HIFEM pelvic floor conditioning session",
      packageRemaining: "5 of 10 sessions",
      phone: "+91 98208 77665"
    },
    {
      id: "apt-1902",
      patientId: "p-006",
      patientName: "SHEETAL SHAH",
      doctor: "doc-pelvic-chair",
      service: "PELVIC_CHAIR",
      startTime: "14:30",
      endTime: "15:00",
      timeLabel: "2:30 PM – 3:00 PM",
      status: "booked",
      notes: "Pelvic floor muscle strengthening & posture alignment",
      packageRemaining: "3 of 8 sessions",
      phone: "+91 99200 44321"
    }
  ],

  // Patient directory for search & autocomplete
  patients: [
    { id: "p-001", name: "BASANTI JAIN", mobile: "9820144521", email: "basanti.jain@example.com", package: "AMSK 10 Sessions", sessionsRemaining: 6, lastVisit: "28-08-2026" },
    { id: "p-002", name: "RUKHSHANA SHOLAPURWALA", mobile: "9819211093", email: "rukhshana.s@example.com", package: "Spine Rehab 12", sessionsRemaining: 4, lastVisit: "31-08-2026" },
    { id: "p-003", name: "RANI MHATRE", mobile: "9769388120", email: "rani.mhatre@example.com", package: "Joint Relief 10", sessionsRemaining: 8, lastVisit: "29-08-2026" },
    { id: "p-004", name: "DHARMISHTHA VORA", mobile: "9821099432", email: "dharmishtha@example.com", package: "Post-Op Rehab 6", sessionsRemaining: 2, lastVisit: "01-09-2026" },
    { id: "p-005", name: "MEREENA DESOUZA", mobile: "9833455102", email: "mereena.d@example.com", package: "AMSK Comprehensive", sessionsRemaining: 5, lastVisit: "27-08-2026" },
    { id: "p-006", name: "SHEETAL SHAH", mobile: "9920044321", email: "sheetal.shah@example.com", package: "MSK Care 10", sessionsRemaining: 7, lastVisit: "30-08-2026" },
    { id: "p-007", name: "SHASHIKALA VAIRAGAR", mobile: "9820566781", email: "shashi.v@example.com", package: "Spine Care 8", sessionsRemaining: 3, lastVisit: "26-08-2026" },
    { id: "p-008", name: "DEEPA OBEROI", mobile: "9819922345", email: "deepa.oberoi@example.com", package: "Plantar Protocol 10", sessionsRemaining: 9, lastVisit: "01-09-2026" },
    { id: "p-009", name: "IQBAL SHAIKH", mobile: "9768800192", email: "iqbal.shaikh@example.com", package: "HBOT + AMSK Combo", sessionsRemaining: 1, lastVisit: "29-08-2026" },
    { id: "p-010", name: "VIKRANT KAVITAKE", mobile: "9820012399", email: "vikrant.k@example.com", package: "Sciatica Protocol 10", sessionsRemaining: 3, lastVisit: "31-08-2026" },
    { id: "p-011", name: "SUMIT PAKHALE", mobile: "9920188472", email: "sumit.p@example.com", package: "Decompression Package", sessionsRemaining: 5, lastVisit: "28-08-2026" },
    { id: "p-012", name: "GOVIND KHETAN", mobile: "9833144556", email: "govind.k@example.com", package: "AMSK 8 Sessions", sessionsRemaining: 6, lastVisit: "30-08-2026" },
    { id: "p-013", name: "BOBBY BROOS", mobile: "9820099887", email: "bobby.broos@example.com", package: "VIP Elite Care 15", sessionsRemaining: 12, lastVisit: "01-09-2026" },
    { id: "p-014", name: "POOJA BHANDARY", mobile: "9819544332", email: "pooja.b@example.com", package: "Cervical Spine 8", sessionsRemaining: 4, lastVisit: "29-08-2026" },
    { id: "p-015", name: "BINITA PAREKH", mobile: "9820877665", email: "binita.p@example.com", package: "Women Health 10", sessionsRemaining: 6, lastVisit: "31-08-2026" },
    { id: "p-016", name: "MAMTA OBHAN", mobile: "9820655443", email: "mamta.o@example.com", package: "Laser Pain Relief 10", sessionsRemaining: 4, lastVisit: "28-08-2026" },
    { id: "p-017", name: "KUMKUM MEHTA", mobile: "9920833221", email: "kumkum.m@example.com", package: "Laser Care 10", sessionsRemaining: 7, lastVisit: "30-08-2026" },
    { id: "p-018", name: "FATIMA QURESHI", mobile: "9930299881", email: "fatima.q@example.com", package: "THOR Laser 10", sessionsRemaining: 6, lastVisit: "01-09-2026" },
    { id: "p-019", name: "ARVIND RAVARIYA", mobile: "9819388776", email: "arvind.r@example.com", package: "Spine Care 10", sessionsRemaining: 8, lastVisit: "30-08-2026" },
    { id: "p-020", name: "JASMINE SINGLE", mobile: "9820111335", email: "jasmine.s@example.com", package: "Laser 8 Sessions", sessionsRemaining: 5, lastVisit: "29-08-2026" }
  ]
};
